### ISSUE TITLE
Non-ASCII in server console causes a panic

### ISSUE THREAD

**Issue by mpschorr** [Azuyamat/Boxes#2]
Starting a server with boxes, and the output containing a character outside of ASCII causes Boxes to panic with the following error:

```
thread 'main' panicked at src\minecraft\server.rs:91:33:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }
```

Steps to reproduce:
1. Create a server with `boxes server generate` or `boxes create`
2. Install a plugin that logs a non-ASCII character (for example, Multiverse-Core prints `§` when warning about a deprecated event.)
3. Start the server with `boxes start <server>`
4. Boxes panics due to the non-ASCII character

**Comment by Azuyamat** [comment]
Fixed in latest release.
Using `Stdio::inherit()` instead of `Stdio::piped()`
